config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
             controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                            confirmations: 'users/confirmations', passwords: 'users/passwords',
                            unlocks: 'users/unlocks' }

  root 'articles#index'

  resources :articles do
    resources :comments
  end

  post '/articles/:id/follow', to: 'articles#follow', as: 'follow_user'
  post '/articles/:id/unfollow', to: 'articles#unfollow', as: 'unfollow_user'
  get '/articles/:id/followers', to: 'articles#followers', as: 'user_followers'
  get '/articles/:id/followings', to: 'articles#followings', as: 'user_followings'
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
  belongs_to :followed, foreign_key: :followed_id, class_name: 'User'

  validates :follower, uniqueness: { scope: :followed }
  validates :followed, uniqueness: { scope: :follower }
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<section id="all-links">
  <% if @article.user.id == current_user.id %>
    <div></div>
  <% elsif current_user.followings.include?(@article_author_user) %>
    <h5><%= button_to "Unfollow", unfollow_user_path,  data: {
                    turbo_method: :post,
                  }, class:'btn btn-primary' %></h5>
  <% else %>
    <h5><%= button_to "Follow", follow_user_path, method: "POST", class:'btn btn-primary'  %></h5>
  <% end%>
    <strong>
      <p>
        <%= link_to "Followers: #{@article_author_user.followers.length} ",
           user_followers_path(@article) %>
      </p>
      <p>
        <%= link_to "Following : #{@article_author_user.followings.length}", user_followings_path(@article) %>
      </p>
    </strong>
  <br>
</section>